// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/joke.ts";
import * as $1 from "./routes/index.tsx";
import * as $$0 from "./islands/AccordionProgress.jsx";
import * as $$1 from "./islands/Card.jsx";
import * as $$2 from "./islands/FormContact.jsx";
import * as $$3 from "./islands/MobileHeader.jsx";
import * as $$4 from "./islands/ModalPortfolio.jsx";
import * as $$5 from "./islands/Navigation.jsx";
import * as $$6 from "./islands/Slides.jsx";
import * as $$7 from "./islands/SwitchTheme.tsx";
import * as $$8 from "./islands/TabsQualification.jsx";

const manifest = {
  routes: {
    "./routes/api/joke.ts": $0,
    "./routes/index.tsx": $1,
  },
  islands: {
    "./islands/AccordionProgress.jsx": $$0,
    "./islands/Card.jsx": $$1,
    "./islands/FormContact.jsx": $$2,
    "./islands/MobileHeader.jsx": $$3,
    "./islands/ModalPortfolio.jsx": $$4,
    "./islands/Navigation.jsx": $$5,
    "./islands/Slides.jsx": $$6,
    "./islands/SwitchTheme.tsx": $$7,
    "./islands/TabsQualification.jsx": $$8,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
